### ISSUE TITLE
Request media and web browser navigation keys

### ISSUE THREAD

**Issue by TellNoLies** [TeXitoi/ortho60-keyberon#8]
Hello,
I was going through the layouts and customizing it to how I like my keys and there is no media or web browsing keycodes. 
Examples = KC_MUTE, KC_VOLU, KC_VOLD, KC_MNXT, KC_MPRV, KC_MSTP, KC_MPLY, KC_WBAK, KC_WFWD, and KC_WREF. 
I use these in my workflow not just with browsing but also with my system shortcuts. Is there a way to add them?
Thank you.

**Comment by TeXitoi** [comment]
I've updated the lib to support more keycodes. You need to do a `cargo update` to update the lib.

I think you want:
 - KC_MUTE -> k(Mute)
 -  KC_VOLU -> k(VolUp)
 - KC_VOLD -> k(VolDown)
 -  KC_MNXT -> k(MediaNextSong)
 -  KC_MPRV -> k(MediaPreviousSong
 -  KC_MSTP -> k(MediaStopCD)
 -  KC_MPLY -> k(MediaPlayPause)
 - KC_WBAK -> k(MediaBack)
 - KC_WFWD -> k(MediaForward)
 - KC_WREF -> k(MediaRefresh)

**Comment by TeXitoi** [comment]
Every media key that you need are present and functional?

**Comment by TellNoLies** [comment]
Awesome.  I am going to give these a go. 
Thank you for adding them. :)

**Comment by TeXitoi** [comment]
Have you tried?

**Comment by TellNoLies** [comment]
I have not been able to. I have to resolder the pins on bluepill because
the bottom row randomly stops working and it has gotten worse. But I have
had a lot of things happening that I have not had the chance to fix the
issue. I will let you know when I reflash it with the new codes that you
made.
Thank you.

**Comment by TellNoLies** [comment]
Wow this thing is troublesome.
I had issues with the stlink not flashing the bin. But now I got that to work and flashing. Now the bluepill's green light is just flashing when it is plugged in, via the usb, and is not being recognized as a keyboard again.
I used the new codes and got no errors when building the new bin. I updated cargo before building the new layout and flashing. Might there be something else that I need to update that might be causing issues?
Thank you.

**Comment by TeXitoi** [comment]
Can you send the log while flashing the firmware using dfu?

Flashing led is dfu mode. Thus you must have the bootloader installed, bit not the firmware.

**Comment by TellNoLies** [comment]
```
openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c "init; reset halt; stm32f1x mass_erase 0; program generic_boot20_pc13.bin exit 0x08000000"
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
none separate
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v17 API v2 SWIM v4 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 3.178421
Info : stm32f1x.cpu: hardware has 6 breakpoints, 4 watchpoints
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x080000f0 msp: 0x20005000
Info : device id = 0x20036410
Info : flash size = 128kbytes
stm32x mass erase complete
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0xfffffffe msp: 0xfffffffc
** Programming Started **
auto erase enabled
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x2000003a msp: 0xfffffffc
wrote 7168 bytes from file generic_boot20_pc13.bin in 0.942858s (7.424 KiB/s)
** Programming Finished **
shutdown command invoked
```

**Comment by TellNoLies** [comment]
Do you want me to reflash it back to using dfu, I am not sure what you mean.

**Comment by TellNoLies** [comment]
```
sudo dfu-util -d 1eaf:0003 -a 2 -D ortho60-keyberon.bin
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: No DFU capable USB device available
```

**Comment by TeXitoi** [comment]
The openocd command only flash the bootloader while erasing everything else. So after flashing like that, that's normal to have no keyboard and the led blinking. You have to do that only one time, or if you screwed your firmware at the point you can't be in DFU mode.

In the second command, dfu doesn't see any DFU ddevice. Is the led blinking while you type this command? You may need to reset before flashing, or unplugging/replugging, or push reset if detected as a keyboard.

**Comment by TellNoLies** [comment]
The green led is still blinking when I use the dfu command.
I will try connecting it after I run the command.

**Comment by TeXitoi** [comment]
Then check the usb connection. can you see dfu in `dmesg`?

**Comment by TellNoLies** [comment]
I was doing with it plugged into the stlink and not usb. 
I got it to flash the dfu command.

**Comment by TellNoLies** [comment]
I just got to test it again and running the dfu-util command got it to work again with the new layout with the new codes. 
Thank you for your work and help.
