### ISSUE TITLE
Key code multi print when using layers

### ISSUE THREAD

**Issue by TellNoLies** [TeXitoi/ortho60-keyberon#9]
I have been getting the main keycode output in addition to using a layer keycode. So for example, raise + e is - . But instead of just printing out the - it shows up -e. That is just one example, it does it with several of my characters, but -e is the worst offender. I did not notice it doing it before, it was only after the last flash I did of the media key codes. It is also a bit inconsistent and it seems to react to the time after I release the raise key.
Thanks

**Comment by TeXitoi** [comment]
Thé last version is checking the keys without any state. Thus, if you push raise, push e/-, release raise, release e/-, the keyboard will send - then e.

I've correct that, but not yet updated this repo. I'll notify you here when I'll do it by closing this issue. Then, a git pull, recompile and flash via dfu should correct your problem.

17 janv. 2020 02:56:22 Robert <notifications@github.com>:

**Comment by TellNoLies** [comment]
Awesome! 
Thank you very much.

**Comment by TeXitoi** [comment]
Should be fixed now.

As a bonus, you now have HoldTap feature (can do QMK ModTap and LayerTap and SpaceCadet)

https://github.com/TeXitoi/keyberon/blob/master/src/action.rs#L13

Usage example:

https://github.com/TeXitoi/keyberon/blob/master/examples/keyberon60.rs#L78

Please confirm that your issue is fixed.

**Comment by TellNoLies** [comment]
Thank you, 
It is awesome that you are working on making it support more features. It will be rivalling qmk soon enough. :)

**Comment by TellNoLies** [comment]
I am just getting to trying to re-flashing my board. But after running "cargo update" and then running the:
`cargo objcopy --bin ortho60-keyberon --release -- -O binary ortho60-keyberon.bin` I get this error: `error[E0599]: no function or associated item named `new` found for type `keyberon::matrix::PressedKeys<_, _>` in the current scope
   --> src/main.rs:162:52
    |
162 |             debouncer: Debouncer::new(PressedKeys::new(), PressedKeys::new(), 5),
    |                                                    ^^^ function or associated item not found in `keyberon::matrix::PressedKeys<_, _>`

error[E0599]: no function or associated item named `new` found for type `keyberon::matrix::PressedKeys<_, _>` in the current scope
   --> src/main.rs:162:72
    |
162 |             debouncer: Debouncer::new(PressedKeys::new(), PressedKeys::new(), 5),
    |                                                                        ^^^ function or associated item not found in `keyberon::matrix::PressedKeys<_, _>`

error[E0599]: no method named `report_from_pressed` found for type `&mut keyberon::layout::Layout` in the current scope
   --> src/main.rs:186:45
    |
186 |             let report = c.resources.layout.report_from_pressed(data.iter_pressed());
    |                                             ^^^^^^^^^^^^^^^^^^^ method not found in `&mut keyberon::layout::Layout`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ortho60-keyberon`.`
I am not sure how to fix this issue.

Thank you for your time and help.

**Comment by TeXitoi** [comment]
`cargo update` update the dependencies. You have to `git pull` to update the current code. `git pull` may say that Cargo.lock was updated, you can `git checkout Cargo.lock` to get the original all Cargo.lock file.

**Comment by TellNoLies** [comment]
Ah thank you, I did the git pull but got an error about the Cargo.lock file and so it failed to update it. So having the `git checkout Cargo.lock` is the command that I was missing.

**Comment by TeXitoi** [comment]
So, compiled, flashed and working?

**Comment by TellNoLies** [comment]
It still will not update. It says my ortho60-keyberon.bin will be overwritten and then says that I need to commit the changes.

**Comment by TellNoLies** [comment]
I rm ortho60-keyberon.bin and it started building. Now I am just waiting for it to finish building the .bin.

**Comment by TellNoLies** [comment]
I am back to it not wanting to flash with the stlink. I get 'init mode failed (unable to connect to target)' after using `openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c "program ortho60-keyberon.bin exit 0x8000000"`

**Comment by TellNoLies** [comment]
I got it to work. 
I needed to use the`openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c "init; reset halt; stm32f1x mass_erase 0; program generic_boot20_pc13.bin exit 0x08000000"` and then to flash it with the `sudo dfu-util -d 1eaf:0003 -a 2 -D ortho60-keyberon.bin` and now I just need to test it out to make sure that it the issue is fixed with the layers printing the base keycode.

**Comment by TellNoLies** [comment]
Works great!!
Now I need to try out the new features that you added.
Thanks again.

**Comment by TeXitoi** [comment]
Great!

You don't need the stlink anymore, you can directly flash with dfu now.

**Comment by TellNoLies** [comment]
Oh, lol. Not having to use the stlink makes things easier. Thank you for
letting me know.
